print ("")
print ("vvedite kefficenty po formyle")
print ("")
print ("┌ ax+by=c")
print ("┤")
print ("└ dx+ex=f")
print ("")
print ("a=", input())
a= int (input())
print ("b=")
b= int (input())
print ("c=")
c= int (input())
print ("d=")
d= int (input())
print ("e=")
e= int (input())
print ("f=")
f= int (input())
x=(c*e-b*f)/(e*a-d*b)
y=(f-d*x)/e
print ("")
print (x, y)
