print ("")
print ("vvedite kefficenty po formyle")
print ("")
print ("┌ ax+by=c")
print ("┤")
print ("└ dx+ex=f")
print ("")
print ("a=")
a= int (input())
print ("")
print ("b=")
b= int (input())
print ("")
print ("c=")
c= int (input())
print ("")
print ("d=")
d= int (input())
print ("")
print ("e=")
e= int (input())
print ("")
print ("f=")
f= int (input())
x=(c*e-b*f)/(e*a-d*b)
y=(f-d*x)/e
print ("")
print ("x=",x, "y=",y)
