print ("")
print ("vvedite kefficenty po formyle")
print ("")
print ("┌ ax+by=c")
print ("┤")
print ("└ dx+ex=f")
print ("")
print ("a=")
a= int (input())
print ("b=")
b= int (input())
print ("c=")
a= int (input())
print ("a=")
a= int (input())
print ("a=")
a= int (input())
print ("a=")
a= int (input())
x=(c*e-b*f)/(e*a-d*b)
y=(f-d*x)/e
print ("")
print (x, y)
